---
abstract: 'Import from Wikidata for processing with Catmandu'
author:
  - 'Jakob Voß'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-Wikidata
provides:
  Catmandu::Fix::wdata_retain_language:
    file: lib/Catmandu/Fix/wdata_retain_language.pm
    version: 0.03
  Catmandu::Fix::wdata_simplify_claims:
    file: lib/Catmandu/Fix/wdata_simplify_claims.pm
    version: 0.03
  Catmandu::Importer::Wikidata:
    file: lib/Catmandu/Importer/Wikidata.pm
    version: 0.03
  Catmandu::Wikidata:
    file: lib/Catmandu/Wikidata.pm
    version: 0.03
requires:
  Catmandu::Importer::getJSON: 0.2
  Moo: 1.0
  URI::Template: 0
  perl: v5.10.1
resources:
  bugtracker: https://github.com/nichtich/Catmandu-Wikidata/issues
  homepage: https://github.com/nichtich/Catmandu-Wikidata
  repository: https://github.com/nichtich/Catmandu-Wikidata.git
version: 0.03
