---
abstract: 'Import from Wikidata for processing with Catmandu'
author:
  - 'Jakob Voß'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-Wikidata
provides:
  Catmandu::Fix::wdata_limit_language:
    file: lib/Catmandu/Fix/wdata_limit_language.pm
    version: 0.01
  Catmandu::Importer::Wikidata:
    file: lib/Catmandu/Importer/Wikidata.pm
    version: 0.01
  Catmandu::Wikidata:
    file: lib/Catmandu/Wikidata.pm
    version: 0.01
requires:
  Catmandu: 0.7
  Furl: 3.0
  Moo: 1.0
  URI::Escape: 0
  experimental: 0
  perl: v5.10.1
resources:
  bugtracker: https://github.com/nichtich/Catmandu-Wikidata/issues
  homepage: https://github.com/nichtich/Catmandu-Wikidata
  repository: https://github.com/nichtich/Catmandu-Wikidata.git
version: 0.01
